# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0002_auto_20170712_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='company',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='context',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='technology',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
