# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0004_auto_20170712_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('company', models.CharField(max_length=50, null=True)),
                ('context', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, null=True)),
                ('text', models.TextField(null=True)),
                ('keywords', models.TextField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.DeleteModel(
            name='Experiences',
        ),
        migrations.AddField(
            model_name='experience',
            name='modal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webgui.Modal'),
        ),
        migrations.AddField(
            model_name='formation',
            name='modal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webgui.Modal'),
        ),
    ]
