# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-16 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0005_auto_20170715_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='technology',
        ),
        migrations.AddField(
            model_name='skill',
            name='technologies',
            field=models.TextField(null=True),
        ),
    ]
