# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0007_leisure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=30, null=True)),
                ('extension', models.BooleanField(choices=[(True, 'png'), (False, 'jpg')])),
            ],
        ),
    ]
